/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class objectpass_Objectpass */

#ifndef _Included_objectpass_Objectpass
#define _Included_objectpass_Objectpass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     objectpass_Objectpass
 * Method:    modify
 * Signature: (Lobjectpass/SimpleClass;)V
 */
JNIEXPORT void JNICALL Java_objectpass_Objectpass_modify
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
