/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exceptiondemo_Exceptiondemo */

#ifndef _Included_exceptiondemo_Exceptiondemo
#define _Included_exceptiondemo_Exceptiondemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exceptiondemo_Exceptiondemo
 * Method:    divide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_exceptiondemo_Exceptiondemo_divide
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
