/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_app_JNI_App */

#ifndef _Included_jni_app_JNI_App
#define _Included_jni_app_JNI_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_app_JNI_App
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_1app_JNI_1App_display
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
