/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnisort_Jnisort */

#ifndef _Included_jnisort_Jnisort
#define _Included_jnisort_Jnisort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnisort_Jnisort
 * Method:    sorting
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_jnisort_Jnisort_sorting
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
